### ISSUE TITLE
Identical tests

### ISSUE THREAD

**Issue by ppisar** [PerlAlien/Alien-Build#285]
Alien-Build-2.42 containts two test files which are byte-identical:

~~~~
$ sha256sum -b t/alien_build_plugin_decode_dirlisting.t t/alien_build_plugin_decode_dirlistingftpcopy.t
81ea96f1ec6da6c4cae0ce5db892e91a902c2d6dc2e4508b42dc1f480e6130e8 *t/alien_build_plugin_decode_dirlisting.t
81ea96f1ec6da6c4cae0ce5db892e91a902c2d6dc2e4508b42dc1f480e6130e8 *t/alien_build_plugin_decode_dirlistingftpcopy.t
~~~~

I briefly looked into their source and I was unable to find where their file name is used. I believe the two tests are redundant and one of them could be removed.

**Comment by plicease** [comment]
ah.  the `*ftpcopy.t` test is supposed to be similar to the other, but test `Decode::DirListingFtpcopy` instead of `Decode::DirListing`.  Looks like the test got copied in preparation to make the minor changes for testing the other plugin but was never modified to test the other plugin.  #286 + 2.43_01 should fix this.  I will hold off on doing a production release until more important stuff gets merged since in practice the `*Ftpcopy` version of the plugin is rarely if ever used.

Thanks for reporting this.
