### ISSUE TITLE
Generated Install/Files.pm  can't be overridden

### ISSUE THREAD

**Issue by djerius** [PerlAlien/Alien-Build#393]
I run perltidy tests as part of my release process, and the Install/files.pm file generated by Alien::Build::MM::build fails my particular brand of tidyness.

I'm more than happy to provide a replacement, but there doesn't seem to be a mechanism to do so.  

[This is all done via `Dist::Zilla::Plugin::Test::Perl::Critic`, and their doesn't appear to be a mechanism to instruct it to ignore certain files]

**Comment by plicease** [comment]
I'm sorry, I don't quite understand your suggestion.

My feeling is that `[Test::Perl::Critic]` should not be checking files in `blib`, though that will be hard to change now since `all_critic_ok` simply recurses from `.`.  Failing that I think `[Test::Perl::Critic]` should provide an option to test specific files + directories instead of `.`.  For an AB based alien you'd want `lib` and `alienfile`, for dists that have a script directory you would also want to test that as well.

**Comment by djerius** [comment]
> I'm sorry, I don't quite understand your suggestion.

Sorry about that.

Install/Files.pm is generated unconditionally. Instead, only generate it if the author hasn't provided one.

**Comment by plicease** [comment]
> Install/Files.pm is generated unconditionally. Instead, only generate it if the author hasn't provided one.

Got it, I can do that it and it seems reasonable.

Caveat: if we need to add features to `::Install::Files`  then stuff may break in the future, and IMO `[Test::Perl::Critic]` should be fixed.  In practice I don't think we have changed the behavior of `::Install::Files` since it was first implemented.

**Comment by plicease** [comment]
@djerius can you try it with https://github.com/PerlAlien/Alien-Build/pull/397/commits/3e3d53ad42cecc7122a024f2f47197b88f025775 and let me know if that does what you need?

**Comment by plicease** [comment]
@djerius I'm working on a release so I went ahead and merged #397, and will close this, but please LMK if this doesn't do what you need.

**Comment by djerius** [comment]
Hi, sorry for the long silence.  This works for my needs. Thanks!

**Comment by plicease** [comment]
@djerius great!  no worries.  Thanks for the confirmation.
